### ISSUE TITLE
Can trouble Teacher Hu to create a workflow?

### ISSUE THREAD

**Issue by yxf551** [huchenlei/ComfyUI-openpose-editor#1]
Can trouble Teacher Hu to create a workflow, because do not know how to operate in two steps:
1.Stores the json pose object
2.Call /openpose/render API endpoint to convert json to image

**Comment by huchenlei** [comment]
Sorry about that. I probably should have marked explicitly that this repo is still WIP

**Comment by yxf551** [comment]
Thanks Teacher Hu for your answer

**Comment by huchenlei** [comment]
README updated.
