### ISSUE TITLE
Saved image truncated if ratio isn't 1:1

### ISSUE THREAD

**Issue by Maveyyl** [huchenlei/ComfyUI-openpose-editor#2]
Hi and thanks for working on a tool worth it for comfyUI!

So far it seems to me the only usage is to save the image of the pose, load it and put it in the controlnet. Or maybe I am missing something and we can directly export it into the controlnet?

In any case, when exporting the result from the editor, if the ratio asked isn't 1:1 it seems to truncate everything on the edges and let it 100% transparent.

**Comment by huchenlei** [comment]
This node is still WIP as stated in the README. I will find some time to finish it up this week.

**Comment by Maveyyl** [comment]
No stress! Just reporting.
