### ISSUE TITLE
[Question] Which repository the `Render Pose JSON (Human)` node in the example of README comes from?

### ISSUE THREAD

**Issue by SakuraKoi** [huchenlei/ComfyUI-openpose-editor#7]
I tried search but didn't found any custom node pack contains it

**Comment by huchenlei** [comment]
It comes from https://github.com/Fannovel16/comfyui_controlnet_aux. 

It is stated as requirement in README: https://github.com/huchenlei/ComfyUI-openpose-editor#requirement

**Comment by SakuraKoi** [comment]
oh thx! my comfyui_controlnet_aux is outdated XD
